version: 2.1

orbs: 
  ruby: circleci/ruby@1.8.0

jobs:
  build:
    executor: 
      name: ruby/default 
      tag: "3.0.4"
    steps:
      - checkout
      - run:
          command: ruby --version
  gauge_test:
    working_directory: ~/altero
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: 
          command: |
            pwd
workflows:
  first-workflow:
    jobs:
      - build